plugins {
    id 'com.android.application'
}

android {
    namespace 'jp.ippuku.airbridge'
    compileSdk 35

    defaultConfig {
        applicationId 'jp.ippuku.airbridge'
        minSdk 28
        targetSdk 35
        versionCode 3
        versionName '0.2.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
